spring:
  application:
    name: api-gateway

zuul:
  ignoredPatterns: /data-definitions/**/verify, /data-definitions/verify, /v1/admin/**
  routes:
    data-center:
      path: /data/**
      url: http://data
    developer-signin:
      path: /v1/developers/signin
      url: http://developer/
      stripPrefix: true
    developer-signout:
      path: /v1/developers/signout
      url: http://developer/
    developer-signup:
      path: /v1/developers/signup
      url: http://developer/
    developer:
      path: /v1/developers/**
      url: http://developer/v1/developers/
    product:
      path: /v1/products/**
      url: http://product/v1/products/
    device:
      path: /v1/devices/**
      url: http://device/v1/devices/
    user:
      path: /v1/users/**
      url: http://user/v1/users/
    report:
      path: /v1/reports/**
      url: http://report/v1/reports/
    feedback:
      path: /v1/feedbacks/**
      url: http://feedback/v1/feedbacks/
    file:
      path: /v1/files/**
      url: http://file/v1/files/

developer:
  service:
    uri: http://developer/

auth:
  ignored:
    rules:
      - host: localhost
        path: ^(/v1/developers/signin)[a-z0-9\-/]*
        method: POST
      - host: localhost
        path: ^(/v1/developers/signup)[a-z0-9\-/]*
        method: POST
      - host: localhost
        path: ^(/v1/developers/signout)[a-z0-9\-/]*
        method: DELETE
      - host: localhost
        path: ^(/v1/developers/)[0-9a-z]{8}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{12}/verify\?code=[0-9a-zA-Z]{12}
        method: GET
      - host: localhsot
        path: ^(/v1/developers/reset-password)
        method: POST
      - host: localhsot
        path: ^(/v1/developers/reset-password)
        method: PUT