spring:
  application:
    name: api-gateway-user

zuul:
  routes:
    data-center:
      path: /v1/data/**
      url: http://data-center/v1/data/
    device-center:
      path: /v1/devices/**
      url: http://device/v1/devices/
    file:
      path: /v1/files/**
      url: http://file/v1/files
    user:
      path: /v1/users/**
      url: http://user/v1/users/
    feedback:
      path: /v1/feedbacks/**
      url: http://feedback/v1/feedbacks/

auth:
  ignored:
    rules:
      - host: localhost
        path: ^(/v1/users/validationCodes)[a-z0-9\-/]*
        method: POST
      - host: localhost
        path: ^(/v1/users/signin)[a-z0-9\-/]*
        method: POST
      - host: localhost
        path: ^(/v1/users/register)[a-z0-9\-/]*
        method: POST
      - host: localhost
        path: ^(/v1/users/login)[a-z0-9\-/]*
        method: POST
      - host: localhost
        path: ^(/v1/users/resetPassword)[a-z0-9\-/]*
        method: POST