spring:
  application:
    name: api-gateway

zuul:
  ignoredPatterns: /data-definitions/**/verify, /data-definitions/verify
  routes:
    data-center:
      path: /data/**
      url: http://data
    # data-definition:
    #   path: /data-definitions/**
    #   url: http://data-definition
    developer-signin:
      path: /v1/developers/signin
      url: http://developer/
      stripPrefix: true
    developer-signout:
      path: /v1/developers/signout
      url: http://developer/
    developer-signup:
      path: /v1/developers/signup
      url: http://developer/
    developer:
      path: /v1/developers/**
      url: http://developer/
    # developer-open:
    #   path: /developers/open/**
    #   url: http://localhost:8804/developers/open
    # developer-resource:
    #   path: /developers/resource/**
    #   url: http://localhost:8804/developers/resource
    product:
      path: /v1/products/**
      url: http://product
    device:
      path: /devices/**
      url: http://device/
    # file:
    #   path: /files/**
    #   url: http://localhost:8807/files
    user:
      path: /users/**
      url: http://user/
    # report:
    #   path: /reports/**
    #   url: http://localhost:8811/reports

developer:
  service:
    uri: http://developer/

auth:
  ignored:
    rules:
      - host: www.umasuo.com
        path: ^(/auth/anonymous)
        method: GET
      - host: localhost
        path: ^(/v1/developers/signin)[a-z0-9\-/]*
        method: POST
      - host: localhost
        path: ^(/v1/developers/signup)[a-z0-9\-/]*
        method: POST
      - host: localhost
        path: ^(/v1/developers/signout)[a-z0-9\-/]*
        method: DELETE